config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_for :users

  root 'participants#welcome'

  resources :buses, only: %i[create index destroy]

  resources :circle_check_scores, only: %i[create index update]

  resources :maneuvers, only: :index do
    member do
      get :next_participant
      get :previous_participant
    end
  end

  resources :maneuver_participants, except: %i[destroy edit index]

  resources :onboard_judgings, except: %i[destroy edit index] do
    collection do
      get :select_participant
    end
  end

  resources :participants, except: %i[edit new show] do
    collection do
      post :assign_number
      get :scoreboard
      get :welcome
    end
  end

  resources :quiz_scores, only: %i[create index update]

  namespace :admin do
    resources :users, only: %i[destroy index update] do
      collection do
        get :manage
      end
      member do
        post :approve
      end
    end
  end

  post :toggle_scores_lock, to: 'settings#toggle_scores_lock'
  get '/manifest', to: 'rails/pwa#manifest', as: 'pwa_manifest'
end

app/models/maneuver_participant.rb
# frozen_string_literal: true

class ManeuverParticipant < ApplicationRecord
  MIN_SCORE = 0
  MAX_SCORE = 50

  REVERSE_PENALTY = 10
  SPEED_PENALTY = 25
  STOP_PENALTY = 25
  CAD_PENALTY = 50

  include ScoreboardPublisher

  has_paper_trail

  belongs_to :maneuver
  belongs_to :participant

  serialize :obstacles_hit, type: Hash, coder: YAML
  serialize :distances_achieved, type: Hash, coder: YAML

  validates :maneuver, uniqueness: { scope: :participant }
  validates :score, :reversed_direction, presence: true

  before_validation :set_score

  def self.participant_sums
    select('`participant_id`', 'SUM(`score`) AS maneuver_sum').group(:participant_id)
  end

  def self.scoreboard_grouping
    all.group_by(&:participant_id).transform_values do |mps|
      mps.group_by(&:maneuver_id).transform_values(&:first)
    end
  end

  def creator
    user_id = versions.find_by(event: 'create').whodunnit
    User.find_by id: user_id if user_id
  end

  private

  def set_score
    score = MAX_SCORE - obstacle_penalty - distance_penalty - reverse_penalty -
            speed_penalty - additional_stops_penalty - cad_penalty
    assign_attributes score: score.clamp(MIN_SCORE, MAX_SCORE)
  end

  def additional_stops_penalty
    maneuver.counts_additional_stops? && made_additional_stops? ? STOP_PENALTY : 0
  end

  def cad_penalty
    completed_as_designed? ? 0 : CAD_PENALTY
  end

  def distance_penalty
    distances_achieved.each.sum do |(minimum, multiplier), distance|
      [0, (distance - minimum)].max * multiplier
    end
  end

  def obstacle_penalty
    obstacles_hit.each_value.sum { |points, count| points * count }
  end

  def reverse_penalty
    reversed_direction * REVERSE_PENALTY
  end

  def speed_penalty
    maneuver.speed_target.present? && !speed_achieved? ? SPEED_PENALTY : 0
  end
end

app/controllers/maneuver_participants_controller.rb
# frozen_string_literal: true

class ManeuverParticipantsController < ApplicationController
  before_action :find_record, only: %i[show update]
  before_action :find_maneuver_and_participant, only: :create
  before_action(only: %i[create update]) { require_role :judge }

  def show
    @maneuver = @record.maneuver
    @participant = @record.participant
    @page_title = "Judging #{@maneuver.name}"
    @page_subtitle = @participant.display_information(:name, :number, :bus)
  end

  def new
    @maneuver = Maneuver.find_by name: params.require(:maneuver)
    @participant = Participant.find_by number: params.require(:participant)
    @page_title = "Judging #{@maneuver.name}"
    @page_subtitle = @participant.display_information(:name, :number, :bus)

    if @participant.completed? @maneuver
      redirect_to ManeuverParticipant.find_by(maneuver: @maneuver,
                                              participant: @participant)
    end
    @record = ManeuverParticipant.new maneuver: @maneuver,
                                      participant: @participant
  end

  def create
    unless @participant.completed? @maneuver
      attrs = { maneuver: @maneuver, participant: @participant }
      attrs.merge! params.permit(:reversed_direction, :speed_achieved,
                                 :made_additional_stops, :completed_as_designed)
      attrs[:obstacles_hit] = parse_obstacles
      attrs[:distances_achieved] = parse_distance_targets
      ManeuverParticipant.create! attrs
    end
    redirect_to next_participant_maneuver_path(@maneuver)
  end

  def update
    attrs = params.permit(:reversed_direction, :speed_achieved,
                          :made_additional_stops, :completed_as_designed).to_hash
    attrs[:obstacles_hit] = parse_obstacles
    attrs[:distances_achieved] = parse_distance_targets
    @record.update! attrs
    flash[:notice] = t('.success')
    redirect_back_or_to maneuver_participant_path(@record)
  end

  private

  def find_maneuver_and_participant
    @maneuver = Maneuver.find_by id: params.require(:maneuver_id)
    @participant = Participant.find_by id: params.require(:participant_id)
  end

  def find_record
    @record = ManeuverParticipant.find_by id: params.require(:id)
  end

  def parse_obstacles
    obstacles_hit = {}
    obstacle_params = params.select do |key, value|
      key.starts_with?('obstacle') && value.to_i != 0
    end

    obstacle_params.each do |key, value|
      obstacle = Obstacle.find_by id: key.split('_').last.to_i
      obstacles_hit[obstacle.id] = [obstacle.point_value, value.to_i] if obstacle.present?
    end

    obstacles_hit
  end

  def parse_distance_targets
    distances_achieved = {}
    target_params = params.select do |key, _value|
      key.starts_with?('target')
    end

    target_params.each do |key, value|
      target = DistanceTarget.find_by id: key.split('_').last.to_i
      distances_achieved[[target.minimum, target.multiplier]] = value.to_i if target.present?
    end

    distances_achieved
  end
end

app/views/maneuver_participants/_form.html.haml
= form_with model: maneuver_participant do |f|
  = hidden_field_tag :maneuver_id, maneuver.id
  = hidden_field_tag :participant_id, participant.id
  - maneuver.grouped_obstacles.each do |(point_value, type), obstacles|
    .form-group
      = f.label :"obstacle_#{obstacles.first.id}", "#{point_value}-point #{type.pluralize} touched"
      - value = maneuver_participant.obstacles_hit[obstacles.first.id].try(:[], 1) || 0
      = render 'shared/with_increment_buttons' do
        = f.number_field :"obstacle_#{obstacles.first.id}", { value:, in: 0..obstacles.count }
  - maneuver.distance_targets.each do |target|
    .form-group
      = f.label "target_#{target.id}", "#{target.interval_type.capitalize} from #{target.name}"
      - value = maneuver_participant.distances_achieved[[target.minimum, target.multiplier]] || 0
      = render 'shared/with_increment_buttons' do
        = f.number_field "target_#{target.id}", value:, min: 0
  .form-group
    = f.label :reversed_direction, maneuver.name.include?('Reverse') ? 'Extra reverses' : 'Reverses'
    - value = maneuver_participant.reversed_direction || 0
    = render 'shared/with_increment_buttons' do
      = f.number_field :reversed_direction, value:, min: 0
  - if maneuver.speed_target.present?
    .form-group.form-check
      = f.checkbox :speed_achieved, class: 'form-check-input'
      = f.label :speed_achieved, "Achieved #{maneuver.speed_target} mph", class: 'form-check-label'
  - if maneuver.counts_additional_stops?
    .form-group
      = f.checkbox :made_additional_stops, class: 'form-check-input'
      = f.label :made_additional_stops, 'Extra stops?', class: 'form-check-label'
  .form-group.form-check
    = f.checkbox :completed_as_designed, class: 'form-check-input'
    = f.label :completed_as_designed, 'Completed as designed?', class: 'form-check-label'
  = submit_tag submit_text, class: 'btn btn-primary submit'

app/views/maneuver_participants/new.haml
.scoring
  = form_tag maneuver_participants_path, id: 'score_form' do
    = hidden_field_tag :maneuver_id, @maneuver.id
    = hidden_field_tag :participant_id, @participant.id
    - @maneuver.grouped_obstacles.each do |(point_value, type), obstacles|
      .form-group
        = label_tag "#{point_value}-point #{type.pluralize} touched"
        = number_field_tag_with_buttons "obstacle_#{obstacles.first.id}", 0, in: 0..obstacles.count
    - @maneuver.distance_targets.each do |target|
      .form-group
        = label_tag "#{target.interval_type} from #{target.name}"
        = number_field_tag_with_buttons "target_#{target.id}", target.minimum, min: 0
    .form-group
      - if @maneuver.name.include? 'Reverse'
        = label_tag 'Extra reverses'
      - else
        = label_tag 'Reverses'
      = number_field_tag_with_buttons :reversed_direction, 0, min: 0
    - if @maneuver.speed_target.present?
      .form-group
        = label_tag "Achieved #{@maneuver.speed_target} mph"
        = hidden_field_tag :speed_achieved, false
        = giant_check_box_tag :speed_achieved, true, true
    - if @maneuver.counts_additional_stops?
      .form-group
        = label_tag 'Extra stops?'
        = hidden_field_tag :made_additional_stops, false
        = giant_check_box_tag :made_additional_stops, true, false
    .form-group
      = label_tag 'Completed as designed?'
      = hidden_field_tag :completed_as_designed, false
      = giant_check_box_tag :completed_as_designed, true, true
    .form-group
      = submit_tag 'Save & next', class: 'btn btn-primary submit'
      = link_to previous_participant_maneuver_path(@maneuver) do
        %button.btn.btn-secondary.actions{type: :button}
          %i.fas.fa-arrow-left
          %span.d-none.d-sm-inline Previous participant

app/views/maneuver_participants/new.html.haml
.scoring
  = render partial: 'form', locals: { maneuver_participant: @record,
                                      maneuver: @maneuver,
                                      participant: @participant,
                                      submit_text: 'Save & next' }
  = link_to previous_participant_maneuver_path(@maneuver) do
    %button.btn.btn-secondary.actions{ type: :button }
      %i.fa-solid.fa-arrow-left
      %span.d-none.d-sm-inline Previous participant

app/views/maneuver_participants/show.haml
.scoring
  - if current_user.admin? && @record.creator.present?
    %h3 Score recorded by #{@record.creator.name}

  = form_tag maneuver_participant_path(@record), method: :put do
    = hidden_field_tag :maneuver_id, @maneuver.id
    = hidden_field_tag :participant_id, @participant.id
    - @maneuver.grouped_obstacles.each do |(point_value, type), obstacles|
      .form-group
        = label_tag "#{point_value}-point #{type.pluralize} touched"
        - if @record.obstacles_hit.values.first.is_a? Integer
          - value = @record.obstacles_hit[point_value] || 0
        - else
          - value = @record.obstacles_hit[obstacles.first.id].try(:[],1) || 0
        = number_field_tag_with_buttons "obstacle_#{obstacles.first.id}", value, in: 0..obstacles.count
    - @maneuver.distance_targets.each do |target|
      .form-group
        = label_tag "#{target.interval_type} from #{target.name}"
        = number_field_tag_with_buttons "target_#{target.id}",
          @record.distances_achieved[[target.minimum, target.multiplier]],
          min: 0
    .form-group
      - if @maneuver.name.include? 'Reverse'
        = label_tag 'Extra reverses'
      - else
        = label_tag 'Reverses'
      = number_field_tag_with_buttons :reversed_direction, @record.reversed_direction, min: 0
    - if @maneuver.speed_target.present?
      .form-group
        = label_tag "Achieved #{@maneuver.speed_target} mph"
        = hidden_field_tag :speed_achieved, false
        = giant_check_box_tag :speed_achieved, true, @record.speed_achieved?
    - if @maneuver.counts_additional_stops?
      .form-group
        = label_tag 'Extra stops?'
        = hidden_field_tag :made_additional_stops, false
        = giant_check_box_tag :made_additional_stops, true, @record.made_additional_stops?
    .form-group
      = label_tag 'Completed as designed?'
      = hidden_field_tag :completed_as_designed, false
      = giant_check_box_tag :completed_as_designed, true, @record.completed_as_designed?
    .form-group
      = submit_tag 'Save score', class: 'btn btn-primary submit'
      = link_to previous_participant_maneuver_path(@maneuver, relative_to: @participant.number) do
        %button.btn.btn-secondary.actions{type: :button}
          %i.fas.fa-arrow-left
          %span.d-none.d-sm-inline Previous participant
      = link_to next_participant_maneuver_path(@maneuver, relative_to: @participant.number) do
        %button.btn.btn-secondary.actions{type: :button}
          %span.d-none.d-sm-inline Next participant
          %i.fas.fa-arrow-right

app/views/maneuver_participants/show.html.haml
.scoring
  - if current_user.admin? && @record.creator.present?
    %h3 Score recorded by #{@record.creator.name}
  = render partial: 'form', locals: { maneuver_participant: @record,
                                      maneuver: @maneuver,
                                      participant: @participant,
                                      submit_text: 'Save score' }
  = link_to previous_participant_maneuver_path(@maneuver, relative_to: @participant.number) do
    %button.btn.btn-secondary.actions{ type: :button }
      %i.fa-solid.fa-arrow-left
      %span.d-none.d-sm-inline Previous participant
  = link_to next_participant_maneuver_path(@maneuver, relative_to: @participant.number) do
    %button.btn.btn-secondary.actions{ type: :button }
      %span.d-none.d-sm-inline Next participant
      %i.fa-solid.fa-arrow-right