config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_for :users

  root 'participants#welcome'

  resources :buses, only: %i[create index destroy]

  resources :circle_check_scores, only: %i[create index update]

  resources :maneuvers, only: :index do
    member do
      get :next_participant
      get :previous_participant
    end
  end

  resources :maneuver_participants, except: %i[destroy edit index]

  resources :onboard_judgings, except: %i[destroy edit index] do
    collection do
      get :select_participant
    end
  end

  resources :participants, except: %i[edit new show] do
    collection do
      post :assign_number
      get :scoreboard
      get :welcome
    end
  end

  resources :quiz_scores, only: %i[create index update]

  namespace :admin do
    resources :users, only: %i[destroy index update] do
      collection do
        get :manage
      end
      member do
        post :approve
      end
    end
  end

  post :toggle_scores_lock, to: 'settings#toggle_scores_lock'
  get '/manifest', to: 'rails/pwa#manifest', as: 'pwa_manifest'
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  has_paper_trail

  belongs_to :bus, optional: true
  has_many :maneuver_participants, dependent: :destroy
  has_many :maneuvers, through: :maneuver_participants
  has_one :circle_check_score, dependent: :destroy
  has_one :quiz_score, dependent: :destroy
  has_one :onboard_judging, dependent: :destroy
  validates :number, uniqueness: true, if: -> { number.present? }
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :bus, presence: true, if: -> { number.present? }
  validates :number, numericality: { greater_than_or_equal_to: 0 },
                     allow_blank: true

  scope :numbered, -> { where.not number: nil }
  scope :not_numbered, -> { where number: nil }

  after_destroy :update_scoreboard
  after_save :update_scoreboard

  class << self
    def include_circle_check
      select("`#{table_name}`.*")
        .left_joins(:circle_check_score).eager_load(:circle_check_score)
        .merge(CircleCheckScore.with_scores)
    end

    def include_onboard
      select("`#{table_name}`.*",
             "#{null_as_zero('`onboard_judgings`.`score`').to_sql} AS oj_score")
        .left_joins(:onboard_judging).eager_load(:onboard_judging)
    end

    def include_quiz
      select("`#{table_name}`.*")
        .left_joins(:quiz_score).eager_load(:quiz_score)
        .merge(QuizScore.with_scores)
    end

    def include_mp_sum
      joins(<<~JOIN).select("`#{table_name}`.*", 'maneuver_sums.maneuver_sum')
        LEFT OUTER JOIN (#{ManeuverParticipant.participant_sums.to_sql}) maneuver_sums
        ON maneuver_sums.participant_id = `participants`.`id`
      JOIN
    end

    def next_number
      maximum(:number).to_i + 1
    end

    def scoreboard_data
      oj_score = null_as_zero('`onboard_judgings`.`score`').to_sql
      man_sum = null_as_zero('maneuver_sums.maneuver_sum').to_sql
      total_score = "#{man_sum} + #{oj_score} + #{QuizScore.score_calculation.to_sql} + " \
                    "#{CircleCheckScore.score_calculation.to_sql}"

      numbered
        .include_quiz
        .include_circle_check
        .include_onboard
        .include_mp_sum
        .select "#{man_sum} + #{oj_score} AS maneuver_score",
                "#{total_score} AS total_score",
                top?(Arel.sql(total_score).desc, top: 20).to_sql
    end

    def scoreboard_order(sort_order = nil)
      raise ArgumentError unless scoreboard_sorts.key?(sort_order)

      sql, lbda = scoreboard_sorts[sort_order]
      attributes = first&.attributes || {}

      if attributes.key?(sql.keys.first.to_s)
        order sql
      else
        (current_scope || all).sort_by(&lbda)
      end
    end

    def scoreboard_sorts
      { nil => [{ total_score: :desc }, ->(u) { u.total_score * -1 }],
        total_score: [{ total_score: :desc }, ->(u) { u.total_score * -1 }],
        maneuver_score: [{ maneuver_score: :desc }, ->(u) { u.maneuver_score * -1 }],
        participant_name: [{ name: :asc }],
        participant_number: [{ number: :asc }] }
    end
  end

  def as_json(options = {})
    display_name = show_name? ? display_information(:name, :number) : display_information(:number)

    super.merge display_name:, maneuver_score:, total_score:,
                onboard_score: onboard_judging&.score,
                circle_check_score: circle_check_score&.score,
                quiz_score: quiz_score&.score
  end

  def completed?(maneuver)
    maneuvers.include? maneuver
  end

  def maneuver_score
    attributes['maneuver_score'] ||
      (maneuver_participants.sum(:score) + onboard_judging&.score.to_i)
  end

  def display_information(*options)
    # option can be any symbol with a corresponding method on Participant.
    result = options.map do |option|
      case option
      when :bus
        bus.try :number
      when :number
        number.try(:to_s).try :prepend, '#'
      else
        send(option)
      end
    end
    first = result.shift
    last = result.compact.join(', ')
    if last.present?
      "#{first} (#{last})"
    else
      first.to_s
    end
  end

  def total_score
    attributes['total_score'] ||
      (maneuver_score + circle_check_score&.score.to_i + quiz_score&.score.to_i)
  end

  def show_name?
    attributes['top_20'] == 1 ||
      (attributes['top_20'].blank? && Participant.scoreboard_data.reject { |p| p.top_20.zero? }.include?(self))
  end

  private

  def number_changed_from_blank?
    saved_change_to_number? && saved_changes[:number][0].blank?
  end

  def number_changed_to_blank?
    saved_change_to_number? && number.blank?
  end

  def update_scoreboard
    if destroyed? || number_changed_to_blank?
      ScoreboardService.update with: self, type: :remove
    elsif number_changed_from_blank?
      ScoreboardService.update with: self, type: :add
    elsif number?
      ScoreboardService.update with: self
    end
  end
end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController
  before_action :find_user, only: %i[assign_number destroy update]
  skip_before_action :authenticate_user!, only: %i[scoreboard welcome]
  before_action except: %i[index scoreboard welcome] do
    require_role :master_of_ceremonies
  end

  def assign_number
    @participant.update! number: params.require(:number), bus_id: params.require(:bus_id)
    redirect_to participants_path, notice: t('.success')
  end

  def index
    @participants = Participant.order(:created_at).reverse
    @unassigned = Participant.not_numbered.order :name
    @next_number = Participant.next_number
    @buses = Bus.order :number
  end

  def create
    participant = Participant.new user_params
    if participant.save
      flash[:notice] = t('.success')
    else
      flash[:errors] = participant.errors.full_messages
    end
    redirect_to participants_path
  end

  def update
    if @participant.update user_params
      flash[:notice] = t('.success')
    else
      flash[:errors] = @participant.errors.full_messages
    end
    redirect_to participants_path
  end

  def destroy
    @participant.destroy!
    redirect_to participants_path, notice: t('.success')
  end

  def scoreboard
    params.permit :sort_order
    @page_title = 'Scoreboard'
    @can_edit_scores = current_user.try :admin?
    @sort_order = params[:sort_order].try :to_sym

    @maneuvers = Maneuver.order :sequence_number
    return unless (@participants_exist = Participant.numbered.any?)

    @maneuver_participants = ManeuverParticipant.scoreboard_grouping
    @participants = Participant.scoreboard_data.scoreboard_order @sort_order
  end

  def welcome
    @page_title = 'Welcome'
  end

  private

  def find_user
    @participant = Participant.find_by id: params.require(:id)
  end

  def user_params
    params.expect participant: %i[name number bus_id]
  end
end

app/views/participants/_add_to_queue.haml
= render 'shared/title', title: 'Add Participant to Maneuvers Queue'
= form_tag assign_number_participants_path,
  id: 'add_to_queue', class: 'scoring form-inline' do
  = select_tag :id,
    options_from_collection_for_select(@unassigned, :id, :name),
    class: 'form-control mr-3 mb-3 mb-sm-0'
  = select_tag :bus_id,
    options_from_collection_for_select(@buses, :id, :number),
    class: 'form-control mr-3 mb-3 mb-sm-0', include_blank: 'Bus number', required: true
  = number_field_tag_with_buttons :number, @next_number, min: @next_number
  = submit_tag 'Add to maneuver queue', class: 'btn btn-primary ml-md-3 mt-3 mt-sm-0'

app/views/participants/_add_to_queue.html.haml
= render 'shared/title', title: 'Add Participant to Maneuvers Queue'
= form_tag assign_number_participants_path,
           id: 'add_to_queue', class: 'scoring form-inline' do
  = select_tag :id,
               options_from_collection_for_select(unassigned, :id, :name),
               class: 'form-control mr-3 mb-3 mb-sm-0'
  = select_tag :bus_id,
               options_from_collection_for_select(buses, :id, :number),
               class: 'form-control mr-3 mb-3 mb-sm-0', include_blank: 'Bus number', required: true
  = render 'shared/with_increment_buttons' do
    = number_field_tag :number, next_number, min: next_number
  = submit_tag 'Add to maneuver queue', class: 'btn btn-primary ml-md-3 mt-3 mt-sm-0'

app/views/participants/_participant.haml
%tr{data: {participant_id: participant.id}}
  %td.participant{data: {text: participant.number}}
    - if participant.show_name?
      = participant.display_information(:name, :number)
    - else
      = participant.display_information(:number)

  - @maneuvers.each do |maneuver|
    - record = @maneuver_participants.dig(participant.id, maneuver.id)
    %td.maneuver-participant{data: {maneuver_id: maneuver.id}.merge(score_data record)}
      = score_cell record,
        allowed: @can_edit_scores,
        new: new_maneuver_participant_path(maneuver: maneuver.name, participant: participant.number),
        edit: record

  - onboard_judging = participant.onboard_judging
  %td.onboard-judging{data: {onboard_judging_id: onboard_judging.try(:id)}.merge(score_data onboard_judging)}
    = score_cell onboard_judging,
      allowed: @can_edit_scores,
      new: new_onboard_judging_path(participant: participant.number),
      edit: onboard_judging

  %td.maneuver-score{data: {math: 'row-maneuversum', math_mask: '#0'}}= participant.maneuver_score

  - cc = participant.circle_check_score
  %td.circle-check-score{data: {circle_check_score_id: cc.try(:id)}.merge(score_data cc)}
    = score_cell cc,
      allowed: @can_edit_scores,
      new: circle_check_scores_path

  - quiz = participant.quiz_score
  %td.quiz-score{data: {quiz_score_id: quiz.try(:id)}.merge(score_data quiz)}
    = score_cell quiz,
      allowed: @can_edit_scores,
      new: quiz_scores_path

  %td.total-score{data: {math: 'row-subtotalsum'}}= participant.total_score

app/views/participants/_participant.html.haml
%tr{ data: { participant_id: participant.id } }
  %td.participant{ data: { text: participant.number } }
    - if participant.show_name?
      = participant.display_information(:name, :number)
    - else
      = participant.display_information(:number)

  - maneuvers.each do |maneuver|
    - record = maneuver_participants.dig(participant.id, maneuver.id)
    %td.maneuver-participant{ data: { maneuver_id: maneuver.id }.merge(score_data(record)) }
      = score_cell record,
                   allowed: can_edit_scores,
                   new: new_maneuver_participant_path(maneuver: maneuver.name, participant: participant.number),
                   edit: record

  - onboard_judging = participant.onboard_judging
  %td.onboard-judging{ data: { onboard_judging_id: onboard_judging.try(:id) }.merge(score_data(onboard_judging)) }
    = score_cell onboard_judging,
                 allowed: can_edit_scores,
                 new: new_onboard_judging_path(participant: participant.number),
                 edit: onboard_judging

  %td.maneuver-score{ data: { math: 'row-maneuversum', math_mask: '#0' } }= participant.maneuver_score

  - cc = participant.circle_check_score
  %td.circle-check-score{ data: { circle_check_score_id: cc.try(:id) }.merge(score_data(cc)) }
    = score_cell cc,
                 allowed: can_edit_scores,
                 new: circle_check_scores_path

  - quiz = participant.quiz_score
  %td.quiz-score{ data: { quiz_score_id: quiz.try(:id) }.merge(score_data(quiz)) }
    = score_cell quiz,
                 allowed: can_edit_scores,
                 new: quiz_scores_path

  %td.total-score{ data: { math: 'row-subtotalsum' } }= participant.total_score

app/views/participants/_scoreboard.haml
%table.scoreboard
  %tr
    %th Participant
    - @maneuvers.each do |maneuver|
      %th= maneuver.name
    %th Maneuvers total
    %th Circle Check
    %th Quiz
    %th Total score
  - @participants.each do |participant|
    %tr
      %td #{participant.name} (#{participant.number})
      - @maneuvers.each do |maneuver|
        %td
          - record = participant.maneuver_record maneuver
          - if record.present?
            = link_to record.score, record
      %td= participant.maneuver_score
      %td= participant.circle_check_score.try :score
      %td= participant.quiz_score.try :score
      %td= participant.total_score

app/views/participants/_table.haml
.table-responsive
  %table.participants.table
    %thead.thead-dark
      %tr
        %th Name
        %th Number
        %th Bus
        %th
        %th
    %tbody
      = form_with model: Participant.new, local: true do |f|
        %tr#new_participant
          %td= f.text_field :name, placeholder: 'Name', class: 'form-control'
          %td= f.number_field :number, class: 'form-control'
          %td= f.collection_select :bus_id, @buses, :id, :number,
            {include_blank: true}, {class: 'form-control'}
          %td= f.submit 'Add', class: 'btn btn-primary'
          %td
      - @participants.each do |participant|
        %tr{ data: { participant_id: participant.id } }
          = form_with model: participant, namespace: participant.id, local: true do |f|
            %td= f.text_field :name, value: participant.name,
              class: 'form-control', required: true
            %td= f.number_field :number, value: participant.number,
              class: 'form-control'
            %td= f.collection_select :bus_id, @buses, :id, :number,
              {value: participant.try(:bus_id), include_blank: true},
              { class: 'form-control' }
            %td= f.submit 'Save', class: 'btn btn-primary'
          %td= button_to 'Remove', participant_path(participant),
            method: :delete, class: 'btn btn-danger'

app/views/participants/_table.html.haml
.table-responsive
  %table.participants.table
    %thead.thead-dark
      %tr
        %th Name
        %th Number
        %th Bus
        %th
        %th
    %tbody
      = form_with model: Participant.new, local: true do |f|
        %tr#new-participant
          %td= f.text_field :name, placeholder: 'Name', class: 'form-control'
          %td= f.number_field :number, class: 'form-control'
          %td
            = f.collection_select :bus_id, buses, :id, :number,
                                  { include_blank: true }, { class: 'form-control' }
          %td= f.submit 'Add', class: 'btn btn-primary'
          %td
      - participants.each do |participant|
        %tr{ data: { participant_id: participant.id } }
          = form_with model: participant, namespace: participant.id, local: true do |f|
            %td= f.text_field :name, value: participant.name, class: 'form-control', required: true
            %td= f.number_field :number, value: participant.number, class: 'form-control'
            %td
              = f.collection_select :bus_id, buses, :id, :number,
                                    { value: participant.try(:bus_id), include_blank: true },
                                    { class: 'form-control' }
            %td= f.submit 'Save', class: 'btn btn-primary'
          %td
            = button_to 'Remove', participant_path(participant), method: :delete, class: 'btn btn-danger'

app/views/participants/index.haml
.participants
  - if @unassigned.present?
    = render 'add_to_queue'
  - else
    No participants to add to the maneuvers queue.
  = render 'shared/title', title: 'Participants'
  .uniqueness-warning.alert.alert-warning
    Please choose a unique participant number.
  = render 'table'

app/views/participants/index.html.haml
.participants
  - if @unassigned.present?
    = render 'add_to_queue', unassigned: @unassigned, buses: @buses, next_number: @next_number
  - else
    No participants to add to the maneuvers queue.
  = render 'shared/title', title: 'Participants'
  .uniqueness-warning.alert.alert-warning
    Please choose a unique participant number.
  = render 'table', participants: @participants, buses: @buses

app/views/participants/scoreboard.haml
- if @participants_exist
  .scoreboard
    .d-flex.align-items-center
      %button.btn.btn-primary.fullscreen.mr-2
        %i.fas.fa-expand
      - if current_user&.role?(:master_of_ceremonies)
        = form_with url: toggle_scores_lock_path, local: true do |f|
          = f.button class: 'btn btn-primary mr-2' do
            - if Settings.scores_locked?
              Unlock Scores
              %i.fas.fa-lock-open
            - else
              Lock Scores
              %i.fas.fa-lock
      - elsif Settings.scores_locked? && !@archiving
        Scores are locked!
    .scoreboard-content
      - table_classes = %w[scoreboard table table-bordered table-striped table-sm text-center]
      %table{class: table_classes, data: {sortList: sort_list(@sort_order)}}
        %thead.thead-light
          %tr
            %th{data: {sortInitialOrder: 'asc'}} Participant
            - @maneuvers.each do |maneuver|
              %th= maneuver.name
            %th Onboard Judging
            %th Maneuvers total
            %th Circle Check
            %th Quiz
            %th Total score
        %tbody
          = render @participants
      %table#template.d-none
        %tbody
          = render partial: 'participant', locals: { participant: NullParticipant.new }
  = javascript_include_tag 'cable.js' unless @archiving
- else
  %h2 No participants yet

app/views/participants/scoreboard.html.haml
- if @participants_exist
  .scoreboard
    .d-flex.align-items-center
      %button.btn.btn-primary.fullscreen.mr-2
        %i.fa-solid.fa-expand
      - if current_user&.role?(:master_of_ceremonies)
        = form_with url: toggle_scores_lock_path, local: true do |f|
          = f.button class: 'btn btn-primary mr-2' do
            - if Settings.scores_locked?
              Unlock Scores
              %i.fa-solid.fa-lock-open
            - else
              Lock Scores
              %i.fa-solid.fa-lock
      - elsif Settings.scores_locked? && !@archiving
        Scores are locked!
    .scoreboard-content
      - table_classes = %w[scoreboard table table-bordered table-striped table-sm text-center]
      - row_locals = { maneuvers: @maneuvers,
                       maneuver_participants: @maneuver_participants,
                       can_edit_scores: @can_edit_scores }
      %table{ class: table_classes, data: { sortList: sort_list(@sort_order) } }
        %thead.thead-light
          %tr
            %th{ data: { sortInitialOrder: 'asc' } } Participant
            - @maneuvers.each do |maneuver|
              %th= maneuver.name
            %th Onboard Judging
            %th Maneuvers total
            %th Circle Check
            %th Quiz
            %th Total score
        %tbody
          = render @participants, **row_locals
      %table#template.d-none
        %tbody
          = render partial: 'participant', locals: row_locals.merge(participant: NullParticipant.new)
  = javascript_include_tag 'cable.js' unless @archiving
- else
  %h2 No participants yet

app/views/participants/welcome.haml
- event = Rails.configuration.roadeo.event_name
.welcome
  Welcome to the #{Time.now.year}
  = Rails.configuration.roadeo.organization
  #{event} mobile webapp!
  %hr
  - if Participant.any?
    To view the scoreboard, click
    = link_to 'here', scoreboard_participants_path
  - else
    Once the #{event} has begun, you will be able to view the scoreboard here.
  .login-instructions
    If you have signed up to judge the #{event}:
    %ul
      %li
        Click
        = link_to 'here', new_user_registration_path
        to request a login.
      %li
        Once your request has been approved,
        = link_to 'log in', new_user_session_path
        to record maneuver scores.
      %li Enjoy the #{event}!
  .attributions
    = link_to 'This site', 'https://github.com/umts/umasstransit.rodeo'
    designed by
    = link_to 'David Faulkenberry', 'https://github.com/dfaulken'

app/views/participants/welcome.html.haml
- event = Rails.configuration.roadeo.event_name
.welcome
  Welcome to the #{Time.zone.now.year}
  = Rails.configuration.roadeo.organization
  #{event} mobile webapp!
  %hr
  - if Participant.any?
    To view the scoreboard, click
    = link_to 'here', scoreboard_participants_path
    or on the button above.
  - else
    Once the #{event} has begun, you will be able to view the scoreboard here.
  .login-instructions
    If you have signed up to judge the #{event}:
    %ul
      %li
        Click
        = link_to 'here', new_user_registration_path
        to request a login.
      %li
        Once your request has been approved,
        = link_to 'log in', new_user_session_path
        to record maneuver scores.
      %li Enjoy the #{event}!
  .attributions
    = link_to 'This site', 'https://github.com/umts/umasstransit.rodeo'
    designed by
    = link_to 'David Faulkenberry', 'https://github.com/dfaulken'