config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_for :users

  root 'participants#welcome'

  resources :buses, only: %i[create index destroy]

  resources :circle_check_scores, only: %i[create index update]

  resources :maneuvers, only: :index do
    member do
      get :next_participant
      get :previous_participant
    end
  end

  resources :maneuver_participants, except: %i[destroy edit index]

  resources :onboard_judgings, except: %i[destroy edit index] do
    collection do
      get :select_participant
    end
  end

  resources :participants, except: %i[edit new show] do
    collection do
      post :assign_number
      get :scoreboard
      get :welcome
    end
  end

  resources :quiz_scores, only: %i[create index update]

  namespace :admin do
    resources :users, only: %i[destroy index update] do
      collection do
        get :manage
      end
      member do
        post :approve
      end
    end
  end

  post :toggle_scores_lock, to: 'settings#toggle_scores_lock'
  get '/manifest', to: 'rails/pwa#manifest', as: 'pwa_manifest'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_paper_trail

  devise :database_authenticatable, :registerable, :validatable
  validates :name, :email, presence: true, uniqueness: { case_sensitive: false }
  validates :email, format: /\A[^@]+@([^@.]+\.)+[^@.]+\z/
  validates :encrypted_password, presence: true

  scope :unapproved, -> { where.not approved: true }

  def approve!
    update! approved: true, judge: true
  end

  def role?(role)
    admin? || ((master_of_ceremonies? || !Settings.scores_locked?) && send(role))
  end

  # Require admins to approve users once they register.
  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    approved? ? super : :not_approved
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < ApplicationController
    before_action :find_user, except: %i[index manage]
    before_action { require_role :admin }

    def approve
      @user.approve!
      redirect_to manage_admin_users_path, notice: t('.success', name: @user.name)
    end

    def index
      @page_title = 'User Roles'
      @users = User.order(:name)
    end

    def update
      return unless @user.update user_params

      redirect_to admin_users_path, notice: t('.success')
    end

    def destroy
      @user.destroy!
      redirect_back_or_to admin_users_path, notice: t('.success')
    end

    def manage
      @page_title = 'Manage Users'
      @users = User.unapproved.order :name
    end

    private

    def find_user
      @user = User.find_by id: params.require(:id)
    end

    def user_params
      params.expect user: %i[admin quiz_scorer circle_check_scorer master_of_ceremonies judge]
    end
  end
end

app/views/admin/users/index.haml
.table-responsive
  %table.table.table-striped.text-center
    %thead.thead-dark
      %tr
        %th.text-left Name
        %th Admin
        %th Master of Ceremonies
        %th Judge
        %th Quiz Scorer
        %th Circle Check Scorer
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          = form_for user, url: admin_user_path(user), method: :put do |f|
            %td.text-left= user.name
            %td= f.check_box :admin
            %td= f.check_box :master_of_ceremonies
            %td= f.check_box :judge
            %td= f.check_box :quiz_scorer
            %td= f.check_box :circle_check_scorer
            %td
              .actions= f.submit 'Save', class: 'btn btn-primary'
          %td
            .actions= button_to 'Remove', admin_user_path(user), method: :delete, class: 'btn btn-danger'

app/views/admin/users/index.html.haml
.table-responsive
  %table.table.table-striped.text-center
    %thead.thead-dark
      %tr
        %th.text-left Name
        %th Admin
        %th Master of Ceremonies
        %th Judge
        %th Quiz Scorer
        %th Circle Check Scorer
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          = form_for user, url: admin_user_path(user), method: :put do |f|
            %td.text-left= user.name
            %td= f.check_box :admin
            %td= f.check_box :master_of_ceremonies
            %td= f.check_box :judge
            %td= f.check_box :quiz_scorer
            %td= f.check_box :circle_check_scorer
            %td
              .actions= f.submit 'Save', class: 'btn btn-primary'
          %td
            .actions= button_to 'Remove', admin_user_path(user), method: :delete, class: 'btn btn-danger'

app/views/admin/users/manage.haml
- if @users.present?
  .table-responsive
    %table.table.table-striped
      %thead.thead-dark
        %tr
          %th Name
          %th Email
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= user.name
            %td= user.email
            %td.text-right
              = button_to 'Approve', approve_admin_user_path(user),
                class: 'btn btn-success', form_class: 'd-inline'
              = button_to 'Deny', admin_user_path(user), method: :delete,
                class: 'btn btn-danger', form_class: 'd-inline'
- else
  No users with pending approval.

app/views/admin/users/manage.html.haml
- if @users.present?
  .table-responsive
    %table.table.table-striped
      %thead.thead-dark
        %tr
          %th Name
          %th Email
          %th
      %tbody
        - @users.each do |user|
          %tr
            %td= user.name
            %td= user.email
            %td.text-right
              = button_to 'Approve', approve_admin_user_path(user),
                          class: 'btn btn-success', form_class: 'd-inline'
              = button_to 'Deny', admin_user_path(user), method: :delete,
                                                         class: 'btn btn-danger', form_class: 'd-inline'
- else
  No users with pending approval.