config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  devise_for :users

  root 'participants#welcome'

  resources :buses, only: %i[create index destroy]

  resources :circle_check_scores, only: %i[create index update]

  resources :maneuvers, only: :index do
    member do
      get :next_participant
      get :previous_participant
    end
  end

  resources :maneuver_participants, except: %i[destroy edit index]

  resources :onboard_judgings, except: %i[destroy edit index] do
    collection do
      get :select_participant
    end
  end

  resources :participants, except: %i[edit new show] do
    collection do
      post :assign_number
      get :scoreboard
      get :welcome
    end
  end

  resources :quiz_scores, only: %i[create index update]

  namespace :admin do
    resources :users, only: %i[destroy index update] do
      collection do
        get :manage
      end
      member do
        post :approve
      end
    end
  end

  post :toggle_scores_lock, to: 'settings#toggle_scores_lock'
  get '/manifest', to: 'rails/pwa#manifest', as: 'pwa_manifest'
end

app/views/layouts/_navbar.haml
%nav.navbar.navbar-expand-lg
  %a.navbar-brand{href: root_path}= image_tag 'favicon.png'
  %button.navbar-toggler{type: 'button', data: {toggle: 'collapse', target: '#mainnav'}}
    %i.fas.fa-bars
  #mainnav.collapse.navbar-collapse
    - if user_signed_in?
      %ul.navbar-nav.mr-auto
        - if Participant.any?
          = nav_item scoreboard_participants_path, 'Scoreboard'
        = nav_item maneuvers_path, 'Maneuvers', role: :judge
        = nav_item circle_check_scores_path, 'Circle Check', role: :circle_check_scorer
        = nav_item quiz_scores_path, 'Quiz', role: :quiz_scorer
        = nav_item participants_path, 'Participants', role: :master_of_ceremonies
        = nav_item buses_path, 'Buses', role: :master_of_ceremonies
        = nav_item admin_users_path, 'Roles', role: :admin
        = nav_item manage_admin_users_path, role: :admin do
          Manage Users
          - unless User.where(approved: false).count.zero?
            %span.badge.badge-warning
              = User.where(approved: false).count
      .dropdown
        %button.btn.nav-item.dropdown-toggle{data: {toggle: 'dropdown'}}
          = current_user.name
        .dropdown-menu.dropdown-menu-right
          = link_to 'Edit Account', edit_user_registration_path, class: 'dropdown-item'
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item'
    - elsif @archiving
      %h1.navbar-text.ml-auto
        #{Time.now.year} Roadeo Final Results
    - else
      %ul.navbar-nav.ml-auto
        = nav_item new_user_session_path, 'Log in'
        = nav_item new_user_registration_path ,'Request a login'

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg
  %a.navbar-brand{ href: root_path }= image_tag 'icon.svg'
  %button.navbar-toggler{ type: 'button', data: { toggle: 'collapse', target: '#mainnav' } }
    %i.fa-solid.fa-bars
  #mainnav.collapse.navbar-collapse
    - if user_signed_in?
      %ul.navbar-nav.mr-auto
        = nav_item scoreboard_participants_path, 'Scoreboard' if Participant.any?
        = nav_item maneuvers_path, 'Maneuvers', role: :judge
        = nav_item circle_check_scores_path, 'Circle Check', role: :circle_check_scorer
        = nav_item quiz_scores_path, 'Quiz', role: :quiz_scorer
        = nav_item participants_path, 'Participants', role: :master_of_ceremonies
        = nav_item buses_path, 'Buses', role: :master_of_ceremonies
        = nav_item admin_users_path, 'Roles', role: :admin
        = nav_item manage_admin_users_path, role: :admin do
          Manage Users
          - if User.where(approved: false).any?
            %span.badge.badge-warning
              = User.where(approved: false).count
      .dropdown
        %button.btn.nav-item.dropdown-toggle{ data: { toggle: 'dropdown' } }
          = current_user.name
        .dropdown-menu.dropdown-menu-right
          = link_to 'Edit Account', edit_user_registration_path, class: 'dropdown-item'
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'dropdown-item'
    - elsif archiving
      %h1.navbar-text.ml-auto
        #{Time.zone.now.year} Roadeo Final Results
    - else
      %ul.navbar-nav.ml-auto
        = nav_item new_user_session_path, 'Log in'
        = nav_item new_user_registration_path, 'Request a login'

app/views/layouts/application.haml
!!!
%html{lang: 'en'}
  %head
    %meta{charset: 'utf-8'}
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %title= title_text @page_title
    = favicon_link_tag 'favicon.png'
    = stylesheet_link_tag 'application.css', media: 'all'
    = csrf_meta_tags
    = action_cable_meta_tag
  %body
    .container-fluid
      = render 'layouts/navbar'
      - if flash[:error].present?
        .alert.alert-danger= flash[:error]
      - if flash[:errors].present?
        - flash[:errors].each do |error|
          .alert.alert-danger= error
      - if flash[:alert].present?
        .alert.alert-warning= flash[:alert]
      - if flash[:notice].present?
        .alert.alert-success= flash[:notice]
      - if @page_title.present?
        = render 'shared/title', title: @page_title, subtitle: @page_subtitle
      = yield
    = javascript_include_tag 'application.js'

app/views/layouts/application.html.haml
!!!
%html{ lang: 'en' }
  %head
    %meta{ charset: 'utf-8' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }
    %meta{ name: 'apple-mobile-web-app-capable', content: 'yes' }
    %title= title_text @page_title
    = favicon_link_tag 'favicon.ico', sizes: '32x32'
    = favicon_link_tag 'icon.svg', type: 'image/svg+xml'
    = favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png'
    %link{ rel: 'manifest', href: pwa_manifest_path(format: :json) }
    = content_tag :style, nonce: content_security_policy_nonce do
      :plain
        :root {
          --body-bg-color: #{Rails.configuration.roadeo.background};
        }
    = stylesheet_link_tag 'application.css', media: 'all'
    = csrf_meta_tags
    = action_cable_meta_tag
  %body
    .container-fluid
      = render 'layouts/navbar', archiving: @archiving
      - if flash[:error].present?
        .alert.alert-danger= flash[:error]
      - if flash[:errors].present?
        - flash[:errors].each do |error|
          .alert.alert-danger= error
      - if flash[:alert].present?
        .alert.alert-warning= flash[:alert]
      - if flash[:notice].present?
        .alert.alert-success= flash[:notice]
      = render 'shared/title', title: @page_title, subtitle: @page_subtitle if @page_title.present?
      = yield
    = javascript_include_tag 'application.js'